// The action codes (LOGGING.md §3, §4): the draft contract offered to #38 (decided on #44).
// Each code's words are messages.activity.actions[code]; a code with no message fails a test.
export const activityLevels = ['admin', 'partner', 'store', 'storefront', 'system', 'security'] as const
export type ActivityLevel = (typeof activityLevels)[number]

export type ActivityCategory = 'auth' | 'write' | 'support' | 'system' | 'security'

export const activityActions = {
  'staff.signed_in': { level: 'admin', category: 'auth' },
  'staff.signed_out': { level: 'admin', category: 'auth' },
  'staff.sign_in_failed': { level: 'admin', category: 'auth' },
  'staff.reauthenticated': { level: 'admin', category: 'auth' },
  'partner.created': { level: 'admin', category: 'write' },
  'partner.approved': { level: 'admin', category: 'write' },
  'partner.sent_back': { level: 'admin', category: 'write' },
  'partner.paused': { level: 'admin', category: 'write' },
  'partner.resumed': { level: 'admin', category: 'write' },
  'store.suspended': { level: 'admin', category: 'write' },
  'store.restored': { level: 'admin', category: 'write' },
  'store.trial_extended': { level: 'admin', category: 'write' },
  'job.retried': { level: 'admin', category: 'write' },
  'job.undone': { level: 'admin', category: 'write' },
  'staff.invited': { level: 'admin', category: 'write' },
  'staff.role_changed': { level: 'admin', category: 'write' },
  'staff.removed': { level: 'admin', category: 'write' },
  'staff.invitation_resent': { level: 'admin', category: 'write' },
  'staff.invitation_revoked': { level: 'admin', category: 'write' },
  'impersonation.started': { level: 'admin', category: 'support' },
  'impersonation.extended': { level: 'admin', category: 'support' },
  'impersonation.ended': { level: 'admin', category: 'support' },
  'setup_session.started': { level: 'admin', category: 'support' },
  'setup_session.ended': { level: 'admin', category: 'support' },
  'customer.viewed': { level: 'admin', category: 'support' },
  'activity.exported': { level: 'admin', category: 'write' },
  'partner_user.signed_in': { level: 'partner', category: 'auth' },
  'branding.updated': { level: 'partner', category: 'write' },
  'domain.added': { level: 'partner', category: 'write' },
  'plan.created': { level: 'partner', category: 'write' },
  'plan.price_changed': { level: 'partner', category: 'write' },
  'merchant.plan_changed': { level: 'partner', category: 'write' },
  'partner.submitted': { level: 'partner', category: 'write' },
  'support_session.started': { level: 'partner', category: 'support' },
  'person.signed_in': { level: 'store', category: 'auth' },
  'product.updated': { level: 'store', category: 'write' },
  'products.created': { level: 'store', category: 'write' },
  'stock.updated': { level: 'store', category: 'write' },
  'order.refunded': { level: 'store', category: 'write' },
  'storefront.published': { level: 'store', category: 'write' },
  'api_key.created': { level: 'store', category: 'write' },
  'vendor.invited': { level: 'store', category: 'write' },
  'customer.signed_up': { level: 'storefront', category: 'auth' },
  'customer.signed_in': { level: 'storefront', category: 'auth' },
  'customer.sign_in_failed': { level: 'storefront', category: 'auth' },
  'customer.password_reset': { level: 'storefront', category: 'auth' },
  'customer.address_changed': { level: 'storefront', category: 'write' },
  'customer.order_placed': { level: 'storefront', category: 'write' },
  'provisioning.step_failed': { level: 'system', category: 'system' },
  'billing.payment_failed': { level: 'system', category: 'system' },
  'security.sign_in_blocked': { level: 'security', category: 'security' },
  'security.tenant_crossing': { level: 'security', category: 'security' },
  'security.authorization_denied': { level: 'security', category: 'security' },
  'staff.sign_in_refused': { level: 'admin', category: 'auth' },
  'staff.invitation_accepted': { level: 'admin', category: 'auth' },
  'partner.manager_assigned': { level: 'admin', category: 'write' },
  'partner.manager_unassigned': { level: 'admin', category: 'write' },
  'partner.invitation_sent': { level: 'admin', category: 'write' },
  'partner.invitation_resent': { level: 'admin', category: 'write' },
  'partner.approval_recorded': { level: 'admin', category: 'write' },
  'partner.domain_recheck_requested': { level: 'admin', category: 'write' },
  'partner.set_up': { level: 'admin', category: 'write' },
  'partner.offboarding': { level: 'admin', category: 'write' },
  'partner.closed': { level: 'admin', category: 'write' },
  'store.note_added': { level: 'admin', category: 'write' },
  'staff_session.link_reissued': { level: 'admin', category: 'support' },
  'partner_user.signed_out': { level: 'partner', category: 'auth' },
  'partner_user.sign_in_refused': { level: 'partner', category: 'auth' },
  'partner_user.sign_in_locked': { level: 'partner', category: 'auth' },
  'partner_user.second_factor_enrolled': { level: 'partner', category: 'auth' },
  'partner_user.second_factor_refused': { level: 'partner', category: 'auth' },
  'partner_user.reauthenticated': { level: 'partner', category: 'auth' },
  'partner_user.invitation_accepted': { level: 'partner', category: 'auth' },
  'partner_user.password_reset_requested': { level: 'partner', category: 'auth' },
  'partner_user.password_reset': { level: 'partner', category: 'auth' },
  'partner_user.invited': { level: 'partner', category: 'write' },
  'partner_user.role_changed': { level: 'partner', category: 'write' },
  'partner_user.removed': { level: 'partner', category: 'write' },
  'partner_user.invitation_resent': { level: 'partner', category: 'write' },
  'partner_user.invitation_revoked': { level: 'partner', category: 'write' },
  'partner.ownership_transferred': { level: 'partner', category: 'write' },
  'partner.second_factor_policy_set': { level: 'partner', category: 'write' },
  'partner.domain_added': { level: 'partner', category: 'write' },
  'partner.domain_removed': { level: 'partner', category: 'write' },
  'branding.published': { level: 'partner', category: 'write' },
  'branding.file_uploaded': { level: 'partner', category: 'write' },
  'plan.updated': { level: 'partner', category: 'write' },
  'plan.made_live': { level: 'partner', category: 'write' },
  'plan.retired': { level: 'partner', category: 'write' },
  'store.created': { level: 'partner', category: 'write' },
  'store.plan_changed': { level: 'partner', category: 'write' },
  'store.limit_override_added': { level: 'partner', category: 'write' },
  'store.limit_override_removed': { level: 'partner', category: 'write' },
  'store.billing_status_set': { level: 'partner', category: 'write' },
  'store.setup_step_retried': { level: 'partner', category: 'write' },
  'store.invitation_resent': { level: 'partner', category: 'write' },
  'store.domain_recheck_requested': { level: 'partner', category: 'write' },
  'stores.exported': { level: 'partner', category: 'write' },
  'support_session.ended': { level: 'partner', category: 'support' },
  'support_session.link_reissued': { level: 'partner', category: 'support' },
  'partner.domain_status_changed': { level: 'system', category: 'system' },
  'store.domain_status_changed': { level: 'system', category: 'system' },
  'store.suspension_flagged_for_review': { level: 'system', category: 'system' },
  'store.trial_started': { level: 'system', category: 'system' },
  'store.activated': { level: 'system', category: 'system' },
  'store.past_due': { level: 'system', category: 'system' },
  'store.cancelled': { level: 'system', category: 'system' },
} as const satisfies Record<string, { level: ActivityLevel; category: ActivityCategory }>

export type ActionCode = keyof typeof activityActions

export const actionCodes = Object.keys(activityActions) as ActionCode[]

// The API may record a code this console has no words for yet; such an entry still shows (LOGGING.md §3).
export const isActionCode = (code: string): code is ActionCode => Object.hasOwn(activityActions, code)

export const levelOf = (code: ActionCode): ActivityLevel => activityActions[code].level

// The customer's Activity tab offers only a shopper's own account events (decided on #44).
export const shopperActions: readonly ActionCode[] = actionCodes.filter((code) => levelOf(code) === 'storefront')
