/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppCartsRouteImport } from './routes/_app/carts'
import { Route as AppCollectionsRouteImport } from './routes/_app/collections'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppOffersRouteImport } from './routes/_app/offers'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStorefrontRouteImport } from './routes/_app/storefront'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ImpersonateEnterRouteImport } from './routes/impersonate.enter'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppCartsRoute = AppCartsRouteImport.update({
  id: '/carts',
  path: '/carts',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStorefrontRoute = AppStorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const ImpersonateEnterRoute = ImpersonateEnterRouteImport.update({
  id: '/impersonate/enter',
  path: '/impersonate/enter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/stores': typeof StoresRoute
  '/billing': typeof AppBillingRoute
  '/carts': typeof AppCartsRoute
  '/collections': typeof AppCollectionsRoute
  '/customers': typeof AppCustomersRoute
  '/home': typeof AppHomeRoute
  '/offers': typeof AppOffersRoute
  '/orders': typeof AppOrdersRoute
  '/products': typeof AppProductsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/storefront': typeof AppStorefrontRoute
  '/team': typeof AppTeamRoute
  '/sign-in': typeof AuthSignInRoute
  '/impersonate/enter': typeof ImpersonateEnterRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/stores': typeof StoresRoute
  '/billing': typeof AppBillingRoute
  '/carts': typeof AppCartsRoute
  '/collections': typeof AppCollectionsRoute
  '/customers': typeof AppCustomersRoute
  '/home': typeof AppHomeRoute
  '/offers': typeof AppOffersRoute
  '/orders': typeof AppOrdersRoute
  '/products': typeof AppProductsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/storefront': typeof AppStorefrontRoute
  '/team': typeof AppTeamRoute
  '/sign-in': typeof AuthSignInRoute
  '/impersonate/enter': typeof ImpersonateEnterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/stores': typeof StoresRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/carts': typeof AppCartsRoute
  '/_app/collections': typeof AppCollectionsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/offers': typeof AppOffersRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/storefront': typeof AppStorefrontRoute
  '/_app/team': typeof AppTeamRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/impersonate/enter': typeof ImpersonateEnterRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stores'
    | '/billing'
    | '/carts'
    | '/collections'
    | '/customers'
    | '/home'
    | '/offers'
    | '/orders'
    | '/products'
    | '/profile'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/storefront'
    | '/team'
    | '/sign-in'
    | '/impersonate/enter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stores'
    | '/billing'
    | '/carts'
    | '/collections'
    | '/customers'
    | '/home'
    | '/offers'
    | '/orders'
    | '/products'
    | '/profile'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/storefront'
    | '/team'
    | '/sign-in'
    | '/impersonate/enter'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/stores'
    | '/_app/billing'
    | '/_app/carts'
    | '/_app/collections'
    | '/_app/customers'
    | '/_app/home'
    | '/_app/offers'
    | '/_app/orders'
    | '/_app/products'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/storefront'
    | '/_app/team'
    | '/_auth/sign-in'
    | '/impersonate/enter'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  StoresRoute: typeof StoresRoute
  ImpersonateEnterRoute: typeof ImpersonateEnterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carts': {
      id: '/_app/carts'
      path: '/carts'
      fullPath: '/carts'
      preLoaderRoute: typeof AppCartsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections': {
      id: '/_app/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers': {
      id: '/_app/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/storefront': {
      id: '/_app/storefront'
      path: '/storefront'
      fullPath: '/storefront'
      preLoaderRoute: typeof AppStorefrontRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/impersonate/enter': {
      id: '/impersonate/enter'
      path: '/impersonate/enter'
      fullPath: '/impersonate/enter'
      preLoaderRoute: typeof ImpersonateEnterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppCartsRoute: typeof AppCartsRoute
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppHomeRoute: typeof AppHomeRoute
  AppOffersRoute: typeof AppOffersRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStorefrontRoute: typeof AppStorefrontRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppCartsRoute: AppCartsRoute,
  AppCollectionsRoute: AppCollectionsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppHomeRoute: AppHomeRoute,
  AppOffersRoute: AppOffersRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProductsRoute: AppProductsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStorefrontRoute: AppStorefrontRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  StoresRoute: StoresRoute,
  ImpersonateEnterRoute: ImpersonateEnterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
