export { coreRoutes, defineTheme, missingRoutes, requiredParts, type CoreRoute, type RequiredPart, type ThemeManifest } from './contracts/theme'
export { createAnalytics, ga4, googleTagManager, metaPixel, type AnalyticsProvider, type CommerceEvent } from './platform/analytics/analytics'
export { contrastRatio, minContrast, readableOn } from './guard/contrast'
export { createShopClient, ShopApiError, shopHeaders, type ShopClient, type ShopClientOptions, type ShopState } from './platform/api/client'
export { readConsent, writeConsent, type ConsentChoice } from './platform/consent/consent'
export { createI18n, type Translate } from './platform/i18n/i18n'
export { catalogues, en, type Catalogue, type MessageKey } from './platform/i18n/messages'
export { fontNames, fonts, fontStack, type Font } from './platform/media/fonts'
export { formatMoney, type ShopMoney } from './platform/pricing/money'
export { ConsentBanner, LegalNotices, PoweredBy, PreviewBanner, Price, type LegalNotice, type PriceProps } from './platform/required'
export { jsonLdText, seoFor, type Seo, type SeoInput } from './platform/seo/seo'
export { StorefrontProvider, useStorefront, type RenderMode, type Storefront } from './platform/store/context'
export { loadStore, storeQuery, storeSchema, type ShopStoreSettings } from './platform/store/store'
