/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPartnersRouteImport } from './routes/_app/partners'
import { Route as AppProvisioningRouteImport } from './routes/_app/provisioning'
import { Route as AppStatesRouteImport } from './routes/_app/states'
import { Route as AppStoresRouteImport } from './routes/_app/stores'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app/customers_.$customerId'
import { Route as AppPartnersPartnerIdRouteImport } from './routes/_app/partners_.$partnerId'
import { Route as AppPartnersNewRouteImport } from './routes/_app/partners_.new'
import { Route as AppStoresStoreIdRouteImport } from './routes/_app/stores_.$storeId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppProvisioningRoute = AppProvisioningRouteImport.update({
  id: '/provisioning',
  path: '/provisioning',
  getParentRoute: () => AppRoute,
} as any)
const AppStatesRoute = AppStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresRoute = AppStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers_/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersPartnerIdRoute = AppPartnersPartnerIdRouteImport.update({
  id: '/partners_/$partnerId',
  path: '/partners/$partnerId',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersNewRoute = AppPartnersNewRouteImport.update({
  id: '/partners_/new',
  path: '/partners/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresStoreIdRoute = AppStoresStoreIdRouteImport.update({
  id: '/stores_/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/activity': typeof AppActivityRoute
  '/approvals': typeof AppApprovalsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/partners': typeof AppPartnersRoute
  '/provisioning': typeof AppProvisioningRoute
  '/states': typeof AppStatesRoute
  '/stores': typeof AppStoresRoute
  '/sign-in': typeof AuthSignInRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/partners/$partnerId': typeof AppPartnersPartnerIdRoute
  '/partners/new': typeof AppPartnersNewRoute
  '/stores/$storeId': typeof AppStoresStoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/activity': typeof AppActivityRoute
  '/approvals': typeof AppApprovalsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/partners': typeof AppPartnersRoute
  '/provisioning': typeof AppProvisioningRoute
  '/states': typeof AppStatesRoute
  '/stores': typeof AppStoresRoute
  '/sign-in': typeof AuthSignInRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/partners/$partnerId': typeof AppPartnersPartnerIdRoute
  '/partners/new': typeof AppPartnersNewRoute
  '/stores/$storeId': typeof AppStoresStoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/activity': typeof AppActivityRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/partners': typeof AppPartnersRoute
  '/_app/provisioning': typeof AppProvisioningRoute
  '/_app/states': typeof AppStatesRoute
  '/_app/stores': typeof AppStoresRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_app/': typeof AppIndexRoute
  '/_app/customers_/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/partners_/$partnerId': typeof AppPartnersPartnerIdRoute
  '/_app/partners_/new': typeof AppPartnersNewRoute
  '/_app/stores_/$storeId': typeof AppStoresStoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/approvals'
    | '/customers'
    | '/dashboard'
    | '/partners'
    | '/provisioning'
    | '/states'
    | '/stores'
    | '/sign-in'
    | '/customers/$customerId'
    | '/partners/$partnerId'
    | '/partners/new'
    | '/stores/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/approvals'
    | '/customers'
    | '/dashboard'
    | '/partners'
    | '/provisioning'
    | '/states'
    | '/stores'
    | '/sign-in'
    | '/customers/$customerId'
    | '/partners/$partnerId'
    | '/partners/new'
    | '/stores/$storeId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/activity'
    | '/_app/approvals'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/partners'
    | '/_app/provisioning'
    | '/_app/states'
    | '/_app/stores'
    | '/_auth/sign-in'
    | '/_app/'
    | '/_app/customers_/$customerId'
    | '/_app/partners_/$partnerId'
    | '/_app/partners_/new'
    | '/_app/stores_/$storeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners': {
      id: '/_app/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/provisioning': {
      id: '/_app/provisioning'
      path: '/provisioning'
      fullPath: '/provisioning'
      preLoaderRoute: typeof AppProvisioningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/states': {
      id: '/_app/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof AppStatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stores': {
      id: '/_app/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AppStoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/customers_/$customerId': {
      id: '/_app/customers_/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners_/$partnerId': {
      id: '/_app/partners_/$partnerId'
      path: '/partners/$partnerId'
      fullPath: '/partners/$partnerId'
      preLoaderRoute: typeof AppPartnersPartnerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners_/new': {
      id: '/_app/partners_/new'
      path: '/partners/new'
      fullPath: '/partners/new'
      preLoaderRoute: typeof AppPartnersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stores_/$storeId': {
      id: '/_app/stores_/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof AppStoresStoreIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPartnersRoute: typeof AppPartnersRoute
  AppProvisioningRoute: typeof AppProvisioningRoute
  AppStatesRoute: typeof AppStatesRoute
  AppStoresRoute: typeof AppStoresRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppPartnersPartnerIdRoute: typeof AppPartnersPartnerIdRoute
  AppPartnersNewRoute: typeof AppPartnersNewRoute
  AppStoresStoreIdRoute: typeof AppStoresStoreIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPartnersRoute: AppPartnersRoute,
  AppProvisioningRoute: AppProvisioningRoute,
  AppStatesRoute: AppStatesRoute,
  AppStoresRoute: AppStoresRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppPartnersPartnerIdRoute: AppPartnersPartnerIdRoute,
  AppPartnersNewRoute: AppPartnersNewRoute,
  AppStoresStoreIdRoute: AppStoresStoreIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
